// Auto-generated by scripts/generate-magazines.js. Do not edit manually.
// Add folders named VOL.07, VOL.08, etc. under images/works, then run the generator.
globalThis.EDEN_ESSENTIALS = [
  "essentials (7).jpg",
  "essentials (2).jpg",
  "essentials (3).jpg",
  "essentials (11).jpg",
  "essentials (8).jpg",
  "essentials (9).jpg",
  "essentials (10).jpg",
  "essentials (5).jpg",
  "essentials (6).jpg",
  "essentials (4).jpg",
  "essentials (1).jpg"
];
globalThis.EDEN_MAGAZINES = [
  {
    "id": "vol-01",
    "volume": 1,
    "title": "ISSUE 01",
    "path": "images/works/cover/",
    "pages": [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png"
    ],
    "noShadow": false
  },
  {
    "id": "vol-02",
    "volume": 2,
    "title": "ISSUE 02",
    "path": "images/works/cover2/",
    "pages": [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png"
    ],
    "noShadow": false
  },
  {
    "id": "vol-03",
    "volume": 3,
    "title": "ISSUE 03",
    "path": "images/works/cover3/",
    "pages": [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png"
    ],
    "noShadow": true
  },
  {
    "id": "vol-04",
    "volume": 4,
    "title": "ISSUE 04",
    "path": "images/works/cover4/",
    "pages": [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png",
      "6.png",
      "7.png"
    ],
    "noShadow": false
  },
  {
    "id": "vol-05",
    "volume": 5,
    "title": "ISSUE 05",
    "path": "images/works/cover5/",
    "pages": [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png"
    ],
    "noShadow": false
  },
  {
    "id": "vol-06",
    "volume": 6,
    "title": "ISSUE 06",
    "path": "images/works/cover6/",
    "pages": [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png"
    ],
    "noShadow": false
  },
  {
    "id": "vol-07",
    "volume": 7,
    "title": "ISSUE 07",
    "path": "images/works/cover7/",
    "pages": [
      "1.png",
      "2.mp4",
      "3.png",
      "4.png",
      "5.png"
    ],
    "noShadow": false
  },
  {
    "id": "vol-08",
    "volume": 8,
    "title": "ISSUE 08",
    "path": "images/works/cover8/",
    "pages": [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png"
    ],
    "noShadow": false
  },
  {
    "id": "vol-09",
    "volume": 9,
    "title": "ISSUE 09",
    "path": "images/works/cover9/",
    "pages": [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png"
    ],
    "noShadow": false
  },
  {
    "id": "vol-10",
    "volume": 10,
    "title": "ISSUE 10",
    "path": "images/works/cover10/",
    "pages": [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png"
    ],
    "noShadow": false
  },
  {
    "id": "vol-11",
    "volume": 11,
    "title": "ISSUE 11",
    "path": "images/works/cover11/",
    "pages": [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png"
    ],
    "noShadow": false
  },
  {
    "id": "vol-12",
    "volume": 12,
    "title": "ISSUE 12",
    "path": "images/works/cover12/",
    "pages": [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png"
    ],
    "noShadow": false
  },
  {
    "id": "vol-13",
    "volume": 13,
    "title": "ISSUE 13",
    "path": "images/works/cover13/",
    "pages": [
      "1.png",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg"
    ],
    "noShadow": false
  },
  {
    "id": "vol-14",
    "volume": 14,
    "title": "ISSUE 14",
    "path": "images/works/cover14/",
    "pages": [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png"
    ],
    "noShadow": false
  },
  {
    "id": "vol-15",
    "volume": 15,
    "title": "ISSUE 15",
    "path": "images/works/cover15/",
    "pages": [
      "1.png"
    ],
    "noShadow": false
  },
  {
    "id": "vol-16",
    "volume": 16,
    "title": "ISSUE 16",
    "path": "images/works/cover16/",
    "pages": [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png"
    ],
    "noShadow": false
  },
  {
    "id": "vol-17",
    "volume": 17,
    "title": "ISSUE 17",
    "path": "images/works/cover17/",
    "pages": [
      "1.png"
    ],
    "noShadow": false
  },
  {
    "id": "vol-18",
    "volume": 18,
    "title": "ISSUE 18",
    "path": "images/works/cover18/",
    "pages": [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png",
      "6.png",
      "7.png",
      "8.png",
      "9.png",
      "10.png",
      "11.png"
    ],
    "noShadow": false
  }
];
